# overview graphs of assembly quality, in comparison to other metazoa
# created by WRF
# last modified 2022-12-02

################################################################################
# FIGURE 1 - comparison of 
setwd("~/git/Aphrocallistes_vastus_genome/genomic_overview/")

overview_data_file = "genome_size_stats_metazoa_v1.tab"
overview_data = read.table(overview_data_file, header = TRUE, sep = "\t" )

#                   dark gray     blue         orange       red         green
#                   most genomes  Avas         Omin         human       Ephydatia
point_color_set = c("#11003322", "#101c98dd", "#d76404cc", "#790d1dcc", "#3e740cdd")

n50_over_total = overview_data$N50 / overview_data$Total
is_flagged = overview_data$group_set > 0

pdf(file = "genome_size_stats_metazoa_v2.pdf", width = 4, height = 4, useDingbats = FALSE)
par(mar=c(4,4,1,1))
plot( overview_data$Total, n50_over_total , xlim = c(0,4000), ylim = c(0,0.2) , 
      xlab = "", ylab = "", cex.axis=1.3, cex.lab=1.3, frame.plot = FALSE,
      pch=ifelse(is_flagged,18,16), 
      col=point_color_set[ (overview_data$group_set + 1 )], 
      cex=ifelse(is_flagged,2,1.3) )
text( overview_data$Total[is_flagged], n50_over_total[is_flagged], overview_data$Species[is_flagged],
      font = 3, pos = c(4,4,4,4,3))
segments(0,0.02,4000,0.02, lty = 2, col = c("#00000088"), lwd = 1)
mtext("Total genome size (Mb)", 1, line = 2.3, cex = 1.4)
mtext("N50 / total size", 2, line = 2.3, cex = 1.4)
dev.off()



################################################################################

# overall sequencing coverage
# calculated to 112x
# generated by:
# bedgraph2histo.py -b Aphrocallistes_instagraal_l4_n50_c1_N5.polished_sorted_softmasked.PE-DNA_bowtie2.sorted.bg > Aphrocallistes_instagraal_l4_n50_c1_N5.polished_sorted_softmasked.PE-DNA_bowtie2.sorted.cov_histo.tab

genomecov_data = read.table("Aphrocallistes_instagraal_l4_n50_c1_N5.polished_sorted_softmasked.PE-DNA_bowtie2.sorted.cov_histo.tab", sep = "\t")
plot(genomecov_data$V1, genomecov_data$V2/1000000, type="l", xlim = c(0,250), frame.plot=FALSE,
     xlab="Coverage", ylab="Total Mbp", 
     lwd=4, col="#334596ff",
     cex.axis=1.4, cex.lab=1.4)
text( which.max(genomecov_data$V2), max(genomecov_data$V2)/1e6, 
      paste0(which.max(genomecov_data$V2),"x"), pos = 4, cex = 1.3)


#